name: checkov-action
# https://github.com/bridgecrewio/checkov-action
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Prisma Cloud scan
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: "${{ secrets.PRISMA_API_URL }}"
          BC_API_KEY: "${{ secrets.BC_API_KEY }}"
          BC_SOURCE: 'githubActions'
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          policy_metadata_filter: policy.complianceStandard=jneytchev-fedramp-low

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
